services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ../chroma_data:/data
    ports:
      - "8000:8000"
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4317/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
    depends_on:
      - otel-collector
      - zipkin
  app:
    build: 
      context: .
    command: ["bash"]
    volumes:
      - ../:/app/
    depends_on: [chromadb]
